### ISSUE TITLE
Note on gredient descent error function

### ISSUE THREAD

**Issue by zunzun** [KyleBenelli/linear_regression_gradient_descent_example#1]
In your error function, you calculate the sum of squared error and then divide that by the number of data points.  For any individual regression, the number of data points does not change - so per regression, you are dividing by a constant.  This does not hurt or help the gradient descent - any constant could be used - but it slows down the regression by increasing the total number of calculations per iteration.

Additionally, the gradient descent can use any error function so that, for example, lowest peak absolute value of error can be used - this is less sensitive to outliers, where the outliers would normally yield a large error which is squared, swamping the other data points.  A fitting target of lowest peak absolute error does not square the already large error from outliers.

You could also fit to the lowest relative error rather than lowest absolute error, this is useful where the dynamic range of the dependent variable is large. for example, this data set:
X Y
1 0.1
2 1.0
3 10.0
4 100.0

might better be fit to the lowest relative error in a sensor calibration, so that sensor accuracy at small values is as good as sensor accuracy at large values.  One could take the log of the dependent variable, but then interpretation of fit statistics from the results of the regression is most difficult, as log error was used in their calculation - a common problem of a log regression is used.  In a relative regression there is no log of the dependent variable so interpretation of the fit statistics can proceed normally.

Note that for gradient descent good starting values are required, or the regression may end in an unsatisfactory local error minimum.  I have used a genetic algorithm to provide better starting values by searching error space for initial parameter values, and have seen Markov Chain Monte Carlo (MCMC) used for this - but after getting good results with a genetic algorithm (named "Differential Evolution") I did not use MCMC myself.

**Comment by KyleBenelli** [comment]
Thanks for the helpful feedback! I removed the denominator for the sum of squared error as it slows down the calculations with no current benefit like you said. I think it would be a good idea to add MCMC to find better initial values and use a lowest peak relative value of error function, so I plan to add these to the repository.

**Comment by zunzun** [comment]
As had been said in California, "Totally awesome, gnarly dude!"  In professional correspondences and academic journals, this is usually written as, "Thank you."
